import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import MenuProvider from "../providers/MenuProvider";
import OrderProvider from "../providers/OrderProvider";
import ReservationProvider from "../providers/ReservationProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <MenuProvider>
          <OrderProvider>
            <ReservationProvider>
              <Header/>
              <main>{children}</main>
              <Footer/>
            </ReservationProvider>
          </OrderProvider>
      </MenuProvider>
      </body>
      
    </html>
  );
}
